# Site settings
title: NLP for Economists
subtitle: 
description: |
    MGSE Guest Course, October 2020 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://econnlpcourse.github.io/" # the base hostname & protocol for your site
syllabus: ""#
githubdir: "econnlpcourse/econnlpcourse.github.io"

# Author/user information
title: National Research Council
email: sowmya.vajjala@nrc-cnrc.gc.ca
twitter_username: adyantalamadhya
github_username:  nishkalavallabhi
authorurl: "https://www.linkedin.com/in/sowmya-v-2a38734/"
address: "1200, Montreal Road, Ottawa, Canada"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
